// Generated by CoffeeScript 1.6.2
var escape, hostname, unit;

hostname = location.origin;

escape = function(text) {
  return text.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br>').replace(/\s/g, '&nbsp;').replace(/(http(s)?:\/\/[\d\w\/\.\%\&\?\=\-\#\:\+]+)/g, '<a href="$1" target="_blank">$1</a>');
};

unit = function(data) {
  return "<div class=\"unit\" mark=\"" + data.mark + "\">\n  <div class=\"text\">" + (escape(data.text)) + "</div>\n  <button class=\"link\">del</a>\n</div>";
};

$(function() {
  var add_unit, box, insert_unit, more, s, send, text;

  s = io.connect("" + hostname + ":8001");
  box = $('#box');
  text = $('#text');
  send = $('#send');
  more = $('#more');
  text.focus();
  more.click(function() {
    var children, last;

    children = box.children();
    if (children.length > 1) {
      last = children.last();
      return s.emit('more', last.attr('mark'));
    }
  });
  send.click(function() {
    console.log('s');
    return s.emit('send', text.val());
  });
  add_unit = function(data) {
    var del, elem;

    box.append(unit(data));
    elem = box.children().last();
    del = elem.find('.link');
    return del.click(function() {
      var mark;

      mark = elem.attr('mark');
      s.emit('del', mark);
      return elem.remove();
    });
  };
  insert_unit = function(data) {
    var del, elem;

    console.log('insert_unit', data);
    box.children().first().after(unit(data));
    elem = box.children().first().next();
    del = elem.find('.link');
    return del.click(function() {
      var mark;

      mark = elem.attr('mark');
      s.emit('del', mark);
      return elem.remove();
    });
  };
  s.on('send', function(data) {
    return insert_unit(data);
  });
  s.on('more', function(list) {
    return list.forEach(add_unit);
  });
  s.on('del', function(mark) {
    return $("div[mark='" + mark + "']").remove();
  });
  return $("body").keydown(function(e) {
    if (e.keyCode === 13) {
      console.log(e);
      if (e.ctrlKey) {
        if (!e.altKey) {
          return $("#send").click();
        }
      }
    }
  });
});
