// Generated by CoffeeScript 1.6.2
window.onload = function() {
  var t;

  t = document.querySelector("textarea");
  t.value = localStorage.article || '';
  t.oninput = function() {
    return localStorage.article = t.value;
  };
  return t.focus();
};
